# 设置网站基础URL，用于生成链接和跳转
baseURL = "https://nav.insightai.top/"

# 设置默认语言
languageCode = "zh-CN"

# 设置网站标题
title = "洞见Ai | 看的见的书签导航"

# 设置使用的主题
theme = "WebStack-Hugo"

# 是否保留分类和标签名称的大小写
preserveTaxonomyNames = true

# 禁用路径转换为小写
disablePathToLower = true

# 设置是否使用中日韩字符
hasCJKLanguage = true

# 设置生成的静态文件目录
publishDir = "docs" # 站点静态文件保存目录

# 网站参数设置
[params]
    # 作者信息
    author = "ikirito"

    # 网站描述
    description = "洞见Ai | Hugo WebStack BY ikirito"

    # 网站上传链接（注销）
    upload = "https://wj.qq.com/s2/12053817/3264/" # 左侧导航栏的"网站提交"

    # 关于页面链接（注销）
    about = "https://doks.xazz.top/" # 左侧导航栏的"关于导航"页面(./about)

    # 代码仓库链接（注销）
    repository = "https://github.com/i-kirito"

    # 是否启用网站加载前的预加载动画
    enablePreLoad = true

    # 预加载动画文字，只有在enablePreLoad=true时生效
    textPreLoad = "洞见Ai"

    # 默认展开左侧边导航栏
    expandSidebar = true

    # 网站每个导航地址logo存放地址
    logosPath = "assets/images/logos"

    # logo图片资源不存在或错误时，默认显示的logo
    # 如果为空，将一直加载对应的logo，直至成功
    defaultLogo = "assets/images/logos/default.webp"

    # 默认站点为深色(夜间)模式
    nightMode = false

    # 默认启用一言服务
    yiyan = true

# 搜索引擎优化参数设置
[params.seo]
    # 百度统计 hm.src 的 ID
    baiduhmid = 'efccc04cb44fc49faddac5876180b369'

    # 百度HTML标签验证(baidu-site-verification)
    baiduSiteVer = 'codeva-cCAOSG8MBO'

    # 51.LA 网站统计
    tj51laid = ''
    tj51lack = ''

# 和天气相关的参数设置
[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

# 网站图片路径设置
[params.images]
    favicon = "assets/images/favicon.ico"
    searchImageL = "assets/images/bg-dna.jpg" # 搜索部分浅色背景图
    searchImageD = "assets/images/bg-dna.jpg" # 搜索部分深色背景图
    logoExpandLight = "assets/images/bt8-expand-light.png"
    logoExpandDark = "assets/images/bt8-expand-dark.png"
    logoCollapseLight = "assets/images/favicon.png"
    logoCollapseDark = "assets/images/favicon.png"

# Goldmark渲染器设置
[markup.goldmark.renderer]
    unsafe = true

# 网站页脚相关的内容设置
[params.footer]
    copyright = '本站内容源自互联网，如有内容侵犯权益，请联系站长删除相关内容，联系邮箱：mail@insightai.top <br/><br/><span id="RunTime" style="color:#FC4E27;letter-spacing:2px"></span><br/><br/>&copy; 2023 - <br/>'
